config/routes.rb
Rails.application.routes.draw do

  mount QyWechat::Engine, at: "/"

  root 'qy_apps#index'

  resources :qy_services, only: :receive_ticket do
    post :receive_ticket, on: :collection
  end

  resources :qy_apps

end

app/models/qy_account.rb
class QyAccount < ActiveRecord::Base

  before_create :init_qy_secret_key

  private

    def init_qy_secret_key
      self.qy_secret_key = SecureRandom.hex(8)
    end
end

app/models/qy_app.rb
class QyApp < ActiveRecord::Base

  before_create :init_qy_secret_key

  private

    def init_qy_secret_key
      self.qy_secret_key = SecureRandom.hex(8)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/qy_apps_controller.rb
class QyAppsController < ApplicationController
  before_action :set_qy_app, only: [:show, :edit, :update, :destroy]

  # GET /qy_apps
  # GET /qy_apps.json
  def index
    @qy_apps = QyApp.all
  end

  # GET /qy_apps/1
  # GET /qy_apps/1.json
  def show
  end

  # GET /qy_apps/new
  def new
    @qy_app = QyApp.new
  end

  # GET /qy_apps/1/edit
  def edit
  end

  # POST /qy_apps
  # POST /qy_apps.json
  def create
    @qy_app = QyApp.new(qy_app_params)

    respond_to do |format|
      if @qy_app.save
        format.html { redirect_to @qy_app, notice: 'Qy account was successfully created.' }
        format.json { render :show, status: :created, location: @qy_app }
      else
        format.html { render :new }
        format.json { render json: @qy_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qy_apps/1
  # PATCH/PUT /qy_apps/1.json
  def update
    respond_to do |format|
      if @qy_app.update(qy_app_params)
        format.html { redirect_to @qy_app, notice: 'Qy account was successfully updated.' }
        format.json { render :show, status: :ok, location: @qy_app }
      else
        format.html { render :edit }
        format.json { render json: @qy_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qy_apps/1
  # DELETE /qy_apps/1.json
  def destroy
    @qy_app.destroy
    respond_to do |format|
      format.html { redirect_to qy_apps_url, notice: 'Qy account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qy_app
      @qy_app = QyApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qy_app_params
      params.require(:qy_app).permit(:name, :qy_token, :encoding_aes_key, :corp_id)
    end
end

app/controllers/qy_services_controller.rb
# 应用套件的回调通知处理
# http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AC%AC%E4%B8%89%E6%96%B9%E5%9B%9E%E8%B0%83%E5%8D%8F%E8%AE%AE
class QyServicesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :receive_ticket

  # TODO: 需要创建表: suites
  def receive_ticket
    param_xml = request.body.read
    aes_key   = "NJgquXf6vnYlGpD5APBqlndAq7Nx8fToiEz5Wbaka47"
    aes_key   = Base64.decode64("#{aes_key}=")
    hash      = MultiXml.parse(param_xml)['xml']
    @body_xml = OpenStruct.new(hash)
    suite_id  = "tj86cd0f5b8f7ce20d"
    content   = QyWechat::Prpcrypt.decrypt(aes_key, @body_xml.Encrypt, suite_id)[0]
    hash      = MultiXml.parse(content)["xml"]
    Rails.logger.info hash
    render text: "success"
    # {"SuiteId"=>"tj86cd0f5b8f7ce20d",
    #  "SuiteTicket"=>"Pb5M0PEQFZSNondlK1K_atu2EoobY9piMcQCdE3URiCG3aTwX5WBTQaSsqCzaD-0",
    #  "InfoType"=>"suite_ticket",
    #  "TimeStamp"=>"1426988061"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qy_services_helper.rb
module QyServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QyWechatExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/qy_accounts/_form.html.erb
<%= form_for(@qy_account) do |f| %>
  <% if @qy_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qy_account.errors.count, "error") %> prohibited this qy_account from being saved:</h2>

      <ul>
      <% @qy_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :qy_token %><br>
    <%= f.text_field :qy_token %>
  </div>

  <div class="field">
    <%= f.label :corp_id %><br>
    <%= f.text_field :corp_id %>
  </div>

  <div class="field">
    <%= f.label :encoding_aes_key %><br>
    <%= f.text_field :encoding_aes_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qy_apps/_form.html.erb
<%= form_for(@qy_app) do |f| %>
  <% if @qy_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qy_app.errors.count, "error") %> prohibited this qy_app from being saved:</h2>

      <ul>
      <% @qy_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :qy_token %><br>
    <%= f.text_field :qy_token %>
  </div>

  <div class="field">
    <%= f.label :corp_id %><br>
    <%= f.text_field :corp_id %>
  </div>

  <div class="field">
    <%= f.label :encoding_aes_key %><br>
    <%= f.text_field :encoding_aes_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qy_apps/edit.html.erb
<h1>Editing qy_app</h1>

<%= render 'form' %>

<%= link_to 'Show', @qy_app %> |
<%= link_to 'Back', qy_apps_path %>

app/views/qy_apps/index.html.erb
<h1>Listing qy_apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qy_apps.each do |qy_app| %>
      <tr>
        <td><%= qy_app.name %></td>
        <td><%= qy_wechat_engine.qy_verify_url(qy_app.qy_secret_key) %></td>
        <td><%= link_to 'Show', qy_app %></td>
        <td><%= link_to 'Edit', edit_qy_app_path(qy_app) %></td>
        <td><%= link_to 'Destroy', qy_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qy app', new_qy_app_path %>

app/views/qy_apps/new.html.erb
<h1>New qy_app</h1>

<%= render 'form' %>

<%= link_to 'Back', qy_apps_path %>

app/views/qy_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @qy_app.name %>
</p>

<%= link_to 'Edit', edit_qy_app_path(@qy_app) %> |
<%= link_to 'Back', qy_apps_path %>

app/views/qy_services/receive_ticket.html.erb
<h1>QyServices#receive_ticket</h1>
<p>Find me in app/views/qy_services/receive_ticket.html.erb</p>